### ISSUE TITLE
OnStart Processor isntead of logger filter?

### ISSUE THREAD

**Issue by tsloughter** [salemove/opentelemetry_logger_metadata#2]
Using this `filter` based method means on every log call it will run the filter and do this metadata update, right?

If instead this was setup as an `OnStart`processor it could be done once for all logs that are made.

Will also need an `OnEnd` to remove the span information from the logger metadata.

**Comment by tsloughter** [comment]
Sorry, I am wrong. If `OnStart` were used then the metadata would be updated even when the span is not set to the current span in the process dictionary and it would not be updated when a span is set to the current span, like when calling `with_span` or `set_current_span`.

We need to hook into setting the current span somehow.

**Comment by indrekj** [comment]
> Using this filter based method means on every log call it will run the filter and do this metadata update, right?

I think so yes.

I looked into other hooks as well but I wasn't able to access the current span. The filter seemed to be running in the right context so the current span was always correct.

**Comment by bryannaegele** [comment]
What cost, if any, is there to set logger metadata?

**Comment by tsloughter** [comment]
The Otel SDK actually defines that it should be done like this library is already doing it https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/logging-library-sdk.md#implicit-context-injection

Before looking at this @bryannaegele and I were discussing this issue and he realized it actually needs to be done on context attach, not span start, since a span may become active in a process after it was started elsewhere (another process).

But maybe we should just keep it like the SDK defines where the logger just gets it from the context.

**Comment by tsloughter** [comment]
Closing since OnStart shouldn't be used and am adding logger metadata in `otel_ctx:attach`.
