### ISSUE TITLE
Rewrite in Erlang

### ISSUE THREAD

**Issue by tsloughter** [salemove/opentelemetry_logger_metadata#3]
Since Elixir 1.10 both Elixir and Erlang share the same logger metadata. Meaning if this project were instead in Erlang it could be easily used in projects in any beam based language :)

We probably also want to have this in OpenTelemetry core, so maybe consider a PR to OpenTelemetry itself.

**Comment by indrekj** [comment]
> Since Elixir 1.10 both Elixir and Erlang share the same logger metadata. Meaning if this project were instead in Erlang it could be easily used in projects in any beam based language :)

Yup, indeed. I wrote this to get something quickly running and to test it out (though I have not deployed this anywhere just yet). It should be quite straightforward to write it in Erlang (even more after https://github.com/open-telemetry/opentelemetry-erlang/pull/270 get merged/released).

> We probably also want to have this in OpenTelemetry core, so maybe consider a PR to OpenTelemetry itself.

I thought about this as well but wasn't really sure how to approach this (i.e. where it should live and how it should be set up).

**Comment by indrekj** [comment]
@tsloughter I created https://github.com/salemove/opentelemetry_logger_metadata/pull/4 . Please feel free to review it. My erlang experience is minimal but I think that should work. At least a couple of my manual tests worked and it also worked through Elixir.
