### ISSUE TITLE
OpenTelemetry.register_application_tracer/1 is undefined or private

### ISSUE THREAD

**Issue by ccoqueiro** [salemove/opentelemetry_logger_metadata#7]
Hello all, I installed this library (opentelemetry_logger_metadata and got the error: ** (Mix) Could not start application bible: exited in: Bible.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function OpenTelemetry.register_application_tracer/1 is undefined or private
            (opentelemetry_api 1.0.3) OpenTelemetry.register_application_tracer(:bible)
            (bible 0.1.0) lib/bible/application.ex:9: Bible.Application.start/2
            (kernel 8.3.1) application_master.erl:293: :application_master.start_it_old/4
My mix.exs

defp deps do
    [
      {:phoenix, "~> 1.5.9"},
      {:phoenix_ecto, "~> 4.1"},
      {:ecto_sql, "~> 3.4"},
      {:postgrex, ">= 0.0.0"},
      {:phoenix_html, "~> 2.11"},
      {:phoenix_live_reload, "~> 1.2", only: :dev},
      {:phoenix_live_dashboard, "~> 0.4"},
      {:gettext, "~> 0.11"},
      {:jason, "~> 1.0"},
      {:plug_cowboy, "~> 2.0"},
      {:telemetry, "~> 1.0", override: true},
      {:telemetry_metrics, "~> 0.6"},
      {:telemetry_poller, "~> 1.0", override: true},
      {:opentelemetry_phoenix, "~> 1.0.0-rc.7"},
      {:opentelemetry_ecto, "~> 1.0.0-rc.5"},
      {:opentelemetry_exporter, "~> 1.0.0"},
      {:opentelemetry, "~> 1.0"},
      {:opentelemetry_api, "~> 1.0"},
      {:logger_file_backend, "~> 0.0.10"},
      {:opentelemetry_logger_metadata, "~> 0.1.0"}
    ]
  end

My application.exs:

defmodule Bible.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    OpenTelemetry.register_application_tracer(:bible)
    OpentelemetryLoggerMetadata.setup()
    OpentelemetryPhoenix.setup()
    OpentelemetryEcto.setup([:bible, :repo])
    

Thank you for advance!!

**Comment by indrekj** [comment]
```
OpenTelemetry.register_application_tracer(:bible)
```
isn't need with newer otel versions
